### PR TITLE
Recording the new Union operator for annotation to make None Last

### PR DESCRIPTION
**Pull request by Cheukting**
Recording the new Union operator for annotation to make None Last

- [x] make it work for 2 items only
- [x] make it work for more than 2 items (may involve recursion)
- [x] make it only work with annotations

see task in #22

### CODE REVIEW

**Comment by Zac-HD** [comment]
🎉🎉🎉

I think we'll only want to do this inside annotations, since the | operator might be used in other ways too.

**Comment by Cheukting** [comment]
> 🎉🎉🎉
> 
> I think we'll only want to do this inside annotations, since the | operator might be used in other ways too.

sure, next step

**Comment by Zac-HD** [comment]
Looks great!  Add a test for `arg: int | None | str | float`?  Once that's handled, I'll merge and make a new release 🚀

**Comment by Cheukting** [comment]
> Looks great! Add a test for `arg: int | None | str | float`? Once that's handled, I'll merge and make a new release 🚀

I just added the 3 or more version and it works on something like `var: bool | None | int | str` (see the test file)

**Pull request merged**
