### PR TITLE
update autoflake min version to 2.1.0

### LINKED ISSUE #88: After next `autoflake` release, grab the perf improvement
https://github.com/PyCQA/autoflake/pull/232 is now merged - so the temporary fix of running isort twice can be removed as soon as a new version is released and we update the minimum required version.

(via https://github.com/Zac-HD/shed/issues/78#issuecomment-1464797492)

### PR DESCRIPTION
**Pull request by Cheukting**
closes #88

### CODE REVIEW

**Comment by Cheukting** [comment]
Pass on my machine but not here, will have a look again tomorrow

**Comment by Cheukting** [comment]
```
    assert result == shed(
E   AssertionError: assert 'from os import (\n    waitpid,\n    waitstatus_to_exitcode,\n    walk,\n    write,\n    writev,\n)\n\nprint(\n    waitpid,\n    waitstatus_to_exitcode,\n    walk,\n    write,\n    writev,\n)\n' == 'from os import waitpid, waitstatus_to_exitcode, walk, write, writev\n\nprint(\n    waitpid,\n    waitstatus_to_exitcode,\n    walk,\n    write,\n    writev,\n)\n'
E     - from os import waitpid, waitstatus_to_exitcode, walk, write, writev
E     + from os import (
E     +     waitpid,
E     +     waitstatus_to_exitcode,
E     +     walk,
E     +     write,
E     +     writev,
E     + )
E       
E       print(
E           waitpid,
E           waitstatus_to_exitcode,
E           walk,
E           write,
E           writev,
E       )
____________
```

For some reason it is now multiline :-(

**Comment by Zac-HD** [comment]
[If we look at the file, it's multiline _before_ formatting](https://github.com/Zac-HD/shed/blob/master/tests/recorded/issue75.txt) so I think this is actually a good thing - this change means we're respecting the magic trailing comma when removing unused imports.

So if you run locally and commit that diff we'll be ready to merge!

**Comment by Cheukting** [comment]
This is super funky - first pass it's multiline, 2nd pass it's one line

**Comment by Cheukting** [comment]
So what result do we want? May be we need a 2nd pass for it to work?

**Review by Zac-HD — APPROVED** [review]
Looks great, let's merge 🚀

**Comment by Cheukting** [comment]
It's isort that is being naughty (changing the multiline to a single line). I will have a look upstream then

**Comment by Cheukting** [comment]
To think of it, what we really want is isort to respect the already multiple-line import to remain multiple line, right? In this test case, autoflake (or other tools) remove the un-used import and now it become "too short" for multiple-line (according to sort). I think it makes sense from the perspective of each single tool (and it accidentally cause us problem as we are using them consecutively)

I don't see there is something very wrong with isort, except the fact that if you are only importing a few things it will put it in one line (and sort it) for you. I am not sure if it is a strong enough case to open an issue and PR upstream. We can of cause fix it on our end about the idempotent by running it twice. 

I need your opinion on that @Zac-HD

**Comment by Zac-HD** [comment]
I think non-idempotence is a bug in isort, so constructing a minimal failing example which demonstrates that and reporting it upstream would be good. Until that's fixed, I don't think we can actually get a performance benefit here 😢

**Comment by Cheukting** [comment]
I have opened an issue at isort, I will have a look there to see if I can provide a PR. This one will have to wait I guess

**Comment by Cheukting** [comment]
Screenshot 2023-08-18 at 14 30 39
This is what it looks like after using the setting @alessiamarcolini recommended. @Zac-HD do we want to use it to by pass the upstream issues?

**Comment by Zac-HD** [comment]
If we can get this to work in Shed without needing upstream changes, that would be great!

**Comment by Zac-HD** [comment]
Handled in https://github.com/Zac-HD/shed/pull/105 🙂

**Pull request closed without merging**
